export const EXPENSES_LISTS = 'EXPENSES_LISTS';
export const EXPENSES_DELETE = 'EXPENSES_DELETE';
export const EXPENSES_CREATE = 'EXPENSES_CREATE';

export const INCOME_TYPES = {
	INCOMES_LISTS: 'INCOMES_LISTS',
	INCOMES_DELETE: 'INCOMES_DELETE',
	INCOMES_CREATE: 'INCOMES_CREATE',
};
export const USER_TYPES = {
  USERS_SIGNIN: "USER_SIGNIN",
  USERS_SIGNUP: "USER_SIGNUP",
};

export const NOTES_TYPES = {
  NOTES_CREATE: "NOTES_CREATE",
  NOTES_LISTS: "NOTES_LISTS",
  NOTES_LIST_BY_ID: "NOTES_LIST_BY_ID",
  NOTES_DELETE: "NOTES_DELETE",
};